export const DELETE_ADVERT = 'DELETE_ADVERT';
export const GET_ADVERT_ID = 'GET_ADVERT_ID';
export const DEACTIVATE_ADVERT = 'DEACTIVATE_ADVERT';
export const EDIT_ADVERT = 'EDIT_ADVERT';
export const SET_STATUS_DEACTIVATE_ADVERT ='SET_STATUS_DEACTIVATE_ADVERT';
export const SET_ERROR = 'PROFILE_SET_ERROR';
