export const FIRST_PAGE_DATA = 'FIRST_PAGE_DATA';
export const TWICE_PAGE_DATA = 'TWICE_PAGE_DATA'
export const SET_ERROR = 'REG_SET_ERROR';
export const CONFIRM_REGISTRATION = 'CONFIRM_REGISTRATION'
