export const GET_USER_INFO = 'GET_USER_INFO';
export const GET_USER_ID = 'GET_USER_ID';
export const GET_PROFILE_INFO = 'GET_PROFILE_INFO';
export const SET_PROFILE_INFO = 'SET_PROFILE_INFO';
export const DELETE_USER_INFO = 'DELETE_USER_INFO'
export const SET_ERROR = 'USER_SET_ERROR';
